-- Plantilla de cronograma (EDS) compartida entre todos los usuarios.
-- Reemplaza el almacenamiento local (localStorage) que tenía cada usuario por separado.

create table if not exists public.reporte_cronograma (
  id bigint generated by default as identity primary key,
  codigo_unico text,
  regional text,
  nombre_eds text,
  negocio text,
  cantidad_islas text,
  total_pq text,
  estado text,
  fecha_programada text,
  dia text,
  agente text,
  observaciones text,
  created_at timestamptz not null default now()
);

create index if not exists idx_reporte_cronograma_codigo
  on public.reporte_cronograma (codigo_unico);

create index if not exists idx_reporte_cronograma_estado
  on public.reporte_cronograma (estado);

-- Metadatos de la última carga (fila única, id = 1).
create table if not exists public.reporte_cronograma_meta (
  id smallint primary key default 1,
  nombre_archivo text,
  actualizado_por text,
  actualizado_en timestamptz not null default now(),
  constraint reporte_cronograma_meta_singleton check (id = 1)
);
insert into public.reporte_cronograma_meta (id)
  values (1) on conflict (id) do nothing;

-- RLS: cualquier usuario autenticado puede ver el cronograma; solo admins
-- (según la tabla usuarios_roles ya existente) pueden subir/editar/limpiar.
alter table public.reporte_cronograma enable row level security;
alter table public.reporte_cronograma_meta enable row level security;

drop policy if exists reporte_cronograma_select on public.reporte_cronograma;
create policy reporte_cronograma_select
  on public.reporte_cronograma for select
  to authenticated
  using (true);

drop policy if exists reporte_cronograma_admin_write on public.reporte_cronograma;
create policy reporte_cronograma_admin_write
  on public.reporte_cronograma for all
  to authenticated
  using (exists (
    select 1 from public.usuarios_roles ur
    where lower(ur.email) = lower(auth.jwt() ->> 'email') and ur.rol = 'admin'
  ))
  with check (exists (
    select 1 from public.usuarios_roles ur
    where lower(ur.email) = lower(auth.jwt() ->> 'email') and ur.rol = 'admin'
  ));

drop policy if exists reporte_cronograma_meta_select on public.reporte_cronograma_meta;
create policy reporte_cronograma_meta_select
  on public.reporte_cronograma_meta for select
  to authenticated
  using (true);

drop policy if exists reporte_cronograma_meta_admin_write on public.reporte_cronograma_meta;
create policy reporte_cronograma_meta_admin_write
  on public.reporte_cronograma_meta for all
  to authenticated
  using (exists (
    select 1 from public.usuarios_roles ur
    where lower(ur.email) = lower(auth.jwt() ->> 'email') and ur.rol = 'admin'
  ))
  with check (exists (
    select 1 from public.usuarios_roles ur
    where lower(ur.email) = lower(auth.jwt() ->> 'email') and ur.rol = 'admin'
  ));
