create table if not exists public.compilados (
  id bigint generated by default as identity primary key,
  nombre_archivo text not null,
  tipo text not null,
  version text,
  tamaño bigint not null default 0,
  ruta_almacenamiento text not null unique,
  usuario_email text,
  usuario_nombre text,
  notas text,
  descargas integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_compilados_created_at
  on public.compilados (created_at desc);

create index if not exists idx_compilados_tipo
  on public.compilados (tipo);

create index if not exists idx_compilados_version
  on public.compilados (version);
